name: Test quickssm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install shellcheck
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y shellcheck
        else
          brew install shellcheck
        fi
      shell: bash

    - name: Run shellcheck
      run: shellcheck ssm src/*.sh tests/*.sh
      
    - name: Make scripts executable
      run: |
        chmod +x ssm
        chmod +x tests/test_ssm.sh
        
    - name: Run tests
      run: ./tests/test_ssm.sh
      
    - name: Test installation script
      run: |
        sudo cp ssm /usr/local/bin/
        ssm version
        ssm check